version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: dogbreeds-postgres
    ports:
      - "5443:5442"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "19960908"
      POSTGRES_DB: DogBreedsDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: